// Generated by typings
// Source: https://raw.githubusercontent.com/types/npm-passport-strategy/707999fe332c7372f21fad3fcd2639b0b0adcf29/lib/strategy.d.ts
declare module '~passport-strategy/lib/strategy' {
abstract class Strategy {
  /**
   * Implement `autheticate()`, performing the necessary operations required by
   * the authentication scheme or protocol being implemented.
   */
  abstract authenticate (this: Strategy.AugmentedStrategy, req: Strategy.Request, options?: any): void;
}

namespace Strategy {
  export interface Request {
    url: string;
    method: string;
    headers: {};
  }

  export class AugmentedStrategy implements Strategy {
    authenticate (req: Strategy.Request, options?: any): void;

    /**
     * Authenticate `user`, with optional `info`.
     *
     * Strategies should call this function to successfully authenticate a
     * user.  `user` should be an object supplied by the application after it
     * has been given an opportunity to verify credentials.  `info` is an
     * optional argument containing additional user information.  This is
     * useful for third-party authentication strategies to pass profile
     * details.
     */
    success (user: any, info: any): void;

    /**
     * Fail authentication, with optional `challenge` and `status`, defaulting
     * to 401.
     *
     * Strategies should call this function to fail an authentication attempt.
     */
    fail (challenge: string, status: number): void;
    fail (status: number): void;

    /**
     * Redirect to `url` with optional `status`, defaulting to 302.
     *
     * Strategies should call this function to redirect the user (via their user
     * agent) to a third-party website for authentication.
     */
    redirect (url: string, status?: number): void;

    /**
     * Pass without making a success or fail decision.
     *
     * Under most circumstances, Strategies should not need to call this
     * function.  It exists primarily to allow previous authentication state
     * to be restored, for example from an HTTP session.
     */
    pass (): void;

    /**
     * Internal error while performing authentication.
     *
     * Strategies should call this function when an internal error occurs
     * during the process of performing authentication; for example, if the
     * user directory is not available.
     */
    error (err: Error): void;
  }
}

export = Strategy;
}
declare module 'passport-strategy/lib/strategy' {
import main = require('~passport-strategy/lib/strategy');
export = main;
}

// Generated by typings
// Source: https://raw.githubusercontent.com/types/npm-passport-strategy/707999fe332c7372f21fad3fcd2639b0b0adcf29/lib/index.d.ts
declare module '~passport-strategy/lib/index' {
import _Strategy = require('~passport-strategy/lib/strategy');

module '~passport-strategy/lib/strategy' {
  export const Strategy: typeof _Strategy;
}

export = _Strategy;
}
declare module 'passport-strategy/lib/index' {
import main = require('~passport-strategy/lib/index');
export = main;
}
declare module 'passport-strategy' {
import main = require('~passport-strategy/lib/index');
export = main;
}
