// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/de1d13bd54cc3a7fb65c04651a68c71bd2968882/deep-freeze-strict/index.d.ts

declare function deepFreeze(o: any): any;

declare namespace deepFreeze { }

declare module "deep-freeze-strict" {
    export = deepFreeze;
}
