#!/usr/bin/env sh

### IMPORT HELPERS ###
source $PWD/script/npm-cmds/helpers/npm-run-helpers.sh

############################################## SCRIPT ##############################################
#
#   npm start     OR     npm run start
#
with_run_env build_all_watch & run_server_watch
