#!/usr/bin/env sh

FILES_TO_WATCH='./build/app/client/**.js ./build/config/**.js ./build/shared/**.js ./build/app/client/**.js'

############################################## SCRIPT ##############################################
#
#   npm run test:client
#
env NODE_PATH=./ npm run build:client;
tsc -p $PWD/app/client/tsconfig.json

mocha build/app/client/**.spec.js
